# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20160629_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
