# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_auto_20160629_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tip',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
