# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_delete_tip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
