# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_auto_20160629_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='totalTips',
            new_name='total_tips',
        ),
    ]
