# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0011_auto_20160629_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Series',
        ),
    ]
