# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_auto_20160629_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(default='', max_length=30)),
                ('resources', models.TextField(default='')),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.Series')),
            ],
        ),
    ]
