# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0014_remove_series_total_tips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tip',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
