# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0016_auto_20160629_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
