# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Group'),
            preserve_default=False,
        ),
    ]
