# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='group',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
